spring:
  application:
    name: service-config

  devtools:
    restart:
      exclude: static/**,public/**,META-INF/resources/**,templates/**

server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/plain

management:
  context-path: /management
  info:
    git:
      mode: full

info:
  name: ${spring.application.name}

security:
  basic:
    path: [ '/**' ]

logging:
  custom:
    request:
      enable: true
    time:
      enable: true
    session:
      enable: true
    user:
      enable: true
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} [rid=%X{rid} sid=%X{sid} \
user=%X{userName}] %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
  level:
    org:
      springframework.web.filter: debug
      hibernate:
        engine: warn #info to show session times
        type: info #trace to show binding parameters
        SQL: info #debug to show generated sql
        stat: debug #debug to show hql query times
